spring:
  application:
    name: project
  profiles:
    active: ${APP_PROFILE:test}

# test
---
    spring:
      config:
        activate:
          on-profile: test

      datasource:
        url:
        username:
        password:

      jpa:
        hibernate:
          show-sql: true
          ddl-auto: create
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
              lob:
                non_contextual_creation: true
